// <auto-generated />
using System;
using CS2Highlights.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS2Highlights.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615195453_AddDemoDetails")]
    partial class AddDemoDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CS2Highlights.Database.Entities.DemoDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("DemoDetails");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.GrenadeEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DmgToEnemies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DmgToTeam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemiesBlinded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrenadeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeammatesBlinded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThrowerSteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tick")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("RoundId");

                    b.ToTable("GrenadeEvents");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.HighlightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClipPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightType")
                        .HasColumnType("TEXT");

                    b.Property<string>("LowlightType")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("RoundId");

                    b.ToTable("Highlights");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.KillEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHeadshot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNoscope")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWallbang")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillerSteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VictimSteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weapon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("RoundId");

                    b.ToTable("KillEvents");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.MatchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedPlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedPlayerSteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "SelectedPlayerSteamId")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.RenderJobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClipPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HighlightId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HighlightId");

                    b.ToTable("RenderJobs");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.RoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinnerSide")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.UserSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.GrenadeEventEntity", b =>
                {
                    b.HasOne("CS2Highlights.Database.Entities.MatchEntity", "Match")
                        .WithMany("GrenadeEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS2Highlights.Database.Entities.RoundEntity", "Round")
                        .WithMany("GrenadeEvents")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.HighlightEntity", b =>
                {
                    b.HasOne("CS2Highlights.Database.Entities.MatchEntity", "Match")
                        .WithMany("Highlights")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS2Highlights.Database.Entities.RoundEntity", "Round")
                        .WithMany("Highlights")
                        .HasForeignKey("RoundId");

                    b.Navigation("Match");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.KillEventEntity", b =>
                {
                    b.HasOne("CS2Highlights.Database.Entities.MatchEntity", "Match")
                        .WithMany("KillEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS2Highlights.Database.Entities.RoundEntity", "Round")
                        .WithMany("KillEvents")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.RenderJobEntity", b =>
                {
                    b.HasOne("CS2Highlights.Database.Entities.HighlightEntity", "Highlight")
                        .WithMany("RenderJobs")
                        .HasForeignKey("HighlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Highlight");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.RoundEntity", b =>
                {
                    b.HasOne("CS2Highlights.Database.Entities.MatchEntity", "Match")
                        .WithMany("Rounds")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.HighlightEntity", b =>
                {
                    b.Navigation("RenderJobs");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.MatchEntity", b =>
                {
                    b.Navigation("GrenadeEvents");

                    b.Navigation("Highlights");

                    b.Navigation("KillEvents");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("CS2Highlights.Database.Entities.RoundEntity", b =>
                {
                    b.Navigation("GrenadeEvents");

                    b.Navigation("Highlights");

                    b.Navigation("KillEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
